### ISSUE TITLE
Add est reading time for blog posts & announcements 

### ISSUE THREAD

**Issue by JasonLovesDoggo** [wlmac/client#104]
See https://dev.to/michaelburrows/calculate-the-estimated-reading-time-of-an-article-using-javascript-2k9l and 
https://medium.com/blogging-guide/how-is-medium-article-read-time-calculated-924420338a85

Use an avg wpm of ~300

**Comment by Trentiumz** [comment]
done on blogs - announcements are rather small, so not sure if reading time is important on it
