### ISSUE TITLE
Fixes needed before release 

### ISSUE THREAD

**Issue by JasonLovesDoggo** [wlmac/client#146]
- [ ] navbar.... too smol & maybe dropdowns?
- [x] cal: very smol / cannot see if there are more than 3 events / no way to zoom expand (make clickable?)
- [x] feat img being fetched via http 
![image](https://github.com/wlmac/client/assets/66544866/9737c2a5-40bd-441e-b060-c2df1eefd98f)

**Comment by rcshim04** [comment]
possibly replace navbar on mobile with full or half screen slide menus

**Comment by Trentiumz** [comment]
http image: that's in the blog post's "image url," which I don't think frontend needs to fix...?

**Comment by Trentiumz** [comment]
navbar: is it still small? I just wanna make sure we haven't fixed this yet
