### ISSUE TITLE
Loading Announcements (Morning Announcements) is very slow

### ISSUE THREAD

**Issue by JasonLovesDoggo** [wlmac/client#150]

**Comment by JasonLovesDoggo** [comment]
You load all anns into memory. 

use pagination properly and only fetch what's needed. for morning anns simply filter start and end date

**Comment by JasonLovesDoggo** [comment]
issue was actually loading all users on startup which should NOT be done.

also load events before users as thats seen.

**Comment by JasonLovesDoggo** [comment]
![image](https://github.com/wlmac/client/assets/66544866/a1e21c87-d8d4-4fca-a05e-130075ca31e0)

**Comment by JasonLovesDoggo** [comment]
In addition 

/events is being requested twice per page load 
![image](https://github.com/wlmac/client/assets/66544866/37dd82d5-74b0-4947-854d-770c00efaf85)

**Comment by JasonLovesDoggo** [comment]
oh also
![image](https://github.com/wlmac/client/assets/66544866/8e2c094a-9b7b-41a6-8278-75ea4be61c10)
these do the same thing lol

> ![image](https://private-user-images.githubusercontent.com/66544866/294711213-a1e21c87-d8d4-4fca-a05e-130075ca31e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODQ4ODQsIm5iZiI6MTcwNDY4NDU4NCwicGF0aCI6Ii82NjU0NDg2Ni8yOTQ3MTEyMTMtYTFlMjFjODctZDhkNC00ZmNhLWEwNWUtMTMwMDc1Y2EzMWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAzMjk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZmQ0OTRkNzcxOTVlZjA3YmFjYmJkNjc2NTVhMDMyODliMjE5NDFkNGRkZTYwMDRkYTZjZmZmOWJjNGYzMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.khDSlVthFCXvmcLwYsRDm1EAkC979q5xzD2PrLQxDtA)

**Comment by Trentiumz** [comment]
should be fixed
