### ISSUE TITLE
Change upcoming events on home page

### ISSUE THREAD

**Issue by skyflaren** [wlmac/client#153]
In order to show something most of the time, perhaps take the (up to) 3 closest events happening within the next 7 days, including ongoing events, sorted by length (shortest events are shown first). This would be so applications with larger windows and an extended holiday break would have less priority than a 30 minute band performance or two hour contest.

**Comment by nir1r7** [comment]
A calendar with all the events in the next 7 days was added during the home page revamp resolving the issue.
