### ISSUE TITLE
Use CSRF for secure forms

### ISSUE THREAD

**Issue by JasonLovesDoggo** [wlmac/client#156]
views like /login store the password in plain text... you want to be using csrf
![image](https://github.com/wlmac/client/assets/66544866/0253328e-57e1-4497-9a01-a84fa65900fd)

**Comment by nyiyui** [comment]
What is the issue here? Are you saying that a CSRF token should be included with the login request?
If so, I don't see why CSRF protection is needed; This API doesn't use cookies AFAIK.

**Comment by nir1r7** [comment]
I also don't see how a CSRF token will help. If we're sending data to the client, browser dev tools will have a way to access it. If I understand correctly, we need to encrypt or hash the password so that the actual password is not visible. Is this what you mean?

**Comment by nyiyui** [comment]
I mean the encryption has to happen on the client, so encryption is kind of moot…hashing the password client-side is also useless unless you don't trust the server with your password,=.

**Comment by JasonLovesDoggo** [comment]
> I also don't see how a CSRF token will help. If we're sending data to the client, browser dev tools will have a way to access it. If I understand correctly, we need to encrypt or hash the password so that the actual password is not visible. Is this what you mean?

As Ken said, hashing client side is kind of useless. 
The point of it isn't to prevent browser Dev from seeing it, it's to prevent a malicious third party site from issuing the same request.

**Comment by nyiyui** [comment]
Rather, my understanding of CSRF is that it prevents attacks where the
browser automatically includes authentication (e.g. cookies). It does so by
including an unguessable-from-other-origins and also
not-automatically-sent-by-the-browser token only available to the origin
you want (i.e. https://client-mock.maclyonsden.com).
