### ISSUE TITLE
User Deletion and Creation 

### ISSUE THREAD

**Issue by Trentiumz** [wlmac/client#158]
- Deletion button in profile
- Don't allow users to create username starting with deleted

**Comment by Trentiumz** [comment]
- big header for when a user is being deleted at every page
- "recover" button for users marked as wanting to be deleted

**Comment by JasonLovesDoggo** [comment]
> * Deletion button in profile
> * Don't allow users to create username starting with deleted

Specifically "deleted" it can be with capital d. That doesn't matter.

**Comment by JasonLovesDoggo** [comment]
I haven't pushed these to prod yet so you won't see the docs on them but just ping me on discord and I'll send the endpoints

**Comment by JasonLovesDoggo** [comment]
One last thing, API3 single user will now also return two Fields: deleted_at which is a timestamp of when the user marked themselves deleted. And is_deleted which is showing if they mark themselves leave it or not (though, theoretically before I push this I could just merge them into one though that is less verbose)

**Comment by Trentiumz** [comment]
User Deletion: e6e71b05f5ab6c8dbd8e41ac6e7196d0c3f6ee8f
for not allowing people to start usernames with deleted, wouldn't it be better to have backend send a "not allowed" to the client? We already have something handling that [here](https://github.com/wlmac/client/blob/b5dcdd9ee0b429d68054ccd4d2dd23293e6a958c/src/components/auth/register/index.tsx#L70)

**Comment by JasonLovesDoggo** [comment]
> User Deletion: [e6e71b0](https://github.com/wlmac/client/commit/e6e71b05f5ab6c8dbd8e41ac6e7196d0c3f6ee8f) for not allowing people to start usernames with deleted, wouldn't it be better to have backend send a "not allowed" to the client? We already have something handling that [here](https://github.com/wlmac/client/blob/b5dcdd9ee0b429d68054ccd4d2dd23293e6a958c/src/components/auth/register/index.tsx#L70)

Sure yeah I could do that. But I just figured it would be more descriptive if front and handled it unless you want me to include a raw message?

**Comment by JasonLovesDoggo** [comment]
E.g. HTTP 400 {message: ", your username cannot start with " deleted"}

**Comment by Trentiumz** [comment]
> E.g. HTTP 400 {message: ", your username cannot start with " deleted"}

ohh that would be really nice - if it doesn't already exist I can make a frontend that gives a notif in that case

For deploying, I think it should be mostly handled tho ?

**Comment by JasonLovesDoggo** [comment]
Actually, upon review this is not needed. :D
