### ISSUE TITLE
superfluous API calls

### ISSUE THREAD

**Issue by nyiyui** [wlmac/client#161]
(copied from internal chat)
visits to pages that shouldn't need some api requests are still making them (/resources fetching tags and orgs)
![image](https://github.com/wlmac/client/assets/45807097/64bfa5a2-8140-43a7-aa97-4826fa2acd34)

**Comment by Trentiumz** [comment]
should be done: 49ccd2fade6dd03d0e9611dec3325bbeb4d802d6
