### ISSUE TITLE
HTTP requests being made

### ISSUE THREAD

**Issue by nyiyui** [wlmac/client#165]
![image](https://github.com/wlmac/client/assets/45807097/83ff7c0e-e310-4fd6-b85e-506f80be725b)

**Comment by Trentiumz** [comment]
This isn't a frontend issue - the link is being stored in the user/blog data and we're just fetching it from the string sent to us from the server... lmk if you think we should have a safeguard for that tho!

**Comment by JasonLovesDoggo** [comment]
what.... as in fetching random links from a response... yes there should be a safeguard

**Comment by Trentiumz** [comment]
BUT https://github.com/wlmac/client/blob/master/src/util/core/misc/gravatar.ts does have an http here :) altho it isn't what's in the screenshot

**Comment by JasonLovesDoggo** [comment]
yeah, that wasn't the point though.

**Comment by Trentiumz** [comment]
done for blogs: c9d2c4b0f90cc57d6f8b58fd60ff285430ddbf96

**Comment by nyiyui** [comment]
@Trentiumz it doesn't seem to work on client-mock right now, is the fix deployed?

**Comment by Trentiumz** [comment]
should be done now ?
