### ISSUE TITLE
Filter announcements by header

### ISSUE THREAD

**Issue by ji-mmyliu** [wlmac/client#53]
Filter announcements by feed header (e.g. school, SAC, etc.)

![image](https://user-images.githubusercontent.com/70064220/233882636-e3a02bb5-4cbb-4ec8-a409-5b6e2322bdf2.png)

**Comment by ApocalypseCalculator** [comment]
Functionality is working, should however fix the race condition to prevent duplicate queries from happening when a double state change happens (e.g. tag gets set to 0 while feed simultaneously changes)

**Comment by ApocalypseCalculator** [comment]
Implemented in 245d5e4 and polished in c06a4b5
